### ISSUE TITLE
Move to QueryParser/QueryBuilder to the uri-parser package ?

### ISSUE THREAD

**Issue by nyamsprod** [thephpleague/uri-components#15]
Currently the `Uri\QueryParser` and `Uri\QueryBuilder` class are bundle in this package. But just like the `Uri\Parser` class, they could be used independently of the URI components object. Someone who do not want use our classes may want to use our parsers.

Shouldn't we transfer the `QueryParser` /`QueryBuilder` class to [the parser package](https://github.com/thephpleague/uri-parser) package.

- Pros: All the basic parsers are located in the same package
- Cons: the uri component will depend on the uri-parser package.

@kelunik thoughts ?

**Comment by kelunik** [comment]
I need to have a look at the query parser, but if it does what I think it does, it should be in its own package instead of being in the parser package. The parser has very few reasons to change, because the underlying spec is an RFC, but there's no such thing for query strings as far as I know?

**Comment by nyamsprod** [comment]
@kelunik indeed, the way query string are parse (ie carrying information in form of `key=value` is not backed by any RFC its just a widely accepted convention.)

**Comment by nyamsprod** [comment]
The query parser/builder classes have been moved to a separate repo https://github.com/thephpleague/uri-query-parser .
