### ISSUE TITLE
Improve Query public API

### ISSUE THREAD

**Issue by nyamsprod** [thephpleague/uri-components#16]
the current API seems to not be very well understood.

- one has to go read the documentation to understand the difference between `getPairs` and `getParams` 
- `getPair` return types can be a `string`, `null` or an array of `string` or `null` values is not very user friendly.

Should we:
- rename the methods
- change the return type so that `getPair` always returns an `array` ?

Last but not least there are some inconsistencies on how pairs are returned. But resolving them would mean BC break. So we need to resolve this while developping the next version

```php
<?php

var_dump([
    'empty array' => Query::createFromPairs([])->getContent(),
    'null array' => Query::createFromPairs([null])->getContent(),
    'empty string array' => Query::createFromPairs([''])->getContent(),
    'empty string array key and value' => Query::createFromPairs(['' => ''])->getContent(),
    'empty string key and null value' => Query::createFromPairs(['' => null])->getContent(),
    'empty string' => (new Query(''))->getPairs(),
]);
```

**Comment by nyamsprod** [comment]
As I'm working on v2 ... Here are the current issues that need a resolution regarding the new Query object. The inconsistencies have already been resolved.

All the code is on the [develop](https://github.com/thephpleague/uri-components/tree/develop/src) branch.

### First issue

in v1 we have the following methods `Query::getParam` and `Query::getParams`. I have remove `Query::getParam` and renamed `Query::getParams` to `Query::toParams` which convert the current `Query` object into an array as `parse_str` would without mangling.

- Is `Query::toParams` a good name ?
- Should we keep `Query::getParams` ? 
- Should we use another name ?

### Second issue

In v2 the Query object is heavily based on [UrlSearchParams](https://developer.mozilla.org/en-US/docs/Web/API/URLSearchParams)

As such, the `QueryParser::parse` and `QueryBuilder::build` methods are updated to better parse and construct the query string.

**In v1 you would get this**
```php
<?php

Uri\parse_query('toto=1&bar=2&toto=2');
//returns ['toto' => ['1', '2'], 'bar' => ['2']];

Uri\build_query(['toto' => ['1', '2'], 'bar' => ['2']]);
//returns 'toto=1&toto=2&bar=2'  ...key/pair order is changed
```
**In v2 you will get this**

```php
<?php

Uri\parse_query('toto=1&bar=2&toto=2');
//returns [['toto' => '1'], ['bar' => '2'], ['toto' => '2']];

Uri\build_query([['toto' => '1'], ['bar' => '2'], ['toto' => '2']]);
//returns 'toto=1&bar=2&toto=2' ...key/pair order is preserved
```

The `Query` object _implements_ `UrlSearchParams` API while keeping the package immutability requirement

UrlSearchParams method | Query method
----------------------|------------------------
 `UrlSearchParams::entries` | `Query::getIterator`
`UrlSearchParams::delete` | `Query:withoutPairs`
`UrlSearchParams::set` |  `Query:withPair`
`UrlSearchParams::append` |  `Query:appendTo`
`UrlSearchParams::keys`   |  no correspondance use the `Query::pairs` method
`UrlSearchParams::values`   |  no correspondance use the `Query::pairs` method
`UrlSearchParams::has` |  `Query:has`
`UrlSearchParams::get` |  `Query:get`
`UrlSearchParams::getAll` |  `Query:getAll`
`UrlSearchParams::sort` |  `Query:ksort`
`UrlSearchParams::toString` |  `Query:__toString`

As you can see in the snippet below `Query::pairs` which differs by one line from `Query::getIterator`  is IMHO more useful.

https://github.com/thephpleague/uri-components/blob/784278d95fb47afbc49460da2f98a4c5333d8843/src/Components/Query.php#L195-L228

So the question becomes  should we :

- keep both methods  `Query::getIterator` and  `Query::pairs` as they are now
- rename the `Query::pairs` into  `Query::getIterator` and remove the current  `Query::getIterator` implementation.
- rename the `Query::pairs` into  `Query::getIterator` and rename the current  `Query::getIterator` into  `Query::entries`.

The last two options means that the following code would throw as `QueryBuilder::build` expects an `array` or a `Traversable` with the structure returned by the current `Query::getIterator`.

```php
<?php
Uri\build_query(new Query('toto=1&bar=2&toto=3'));
```

@kelunik thoughts ?

**Comment by kelunik** [comment]
I don't have a need to keep the order of queries. All _I_ want is a method to get a single query parameter or `null`, so I don't have to real with arrays.

**Comment by nyamsprod** [comment]
then the new `Query::get` method should do that ... returns the first found value for the given key or null otherwise using `Query::getAll` always returns an array containing all the values attached to the given key or the empty array, following UrlSearchParams API.

**Comment by teohhanhui** [comment]
I believe `Query:appendTo` should be combined into `Query::withPair` by adding an optional parameter `$replace`.

**Comment by nyamsprod** [comment]
@teohhanhui combining both method using an optional parameter (ie: a flag) is forbidden in my book. Both methods do something different :  

- `appendTo` append a new value to a pre-exisiting key if the key does not exist it adds the key
- `withPair` adds an new key with a new value if the key is already present that key and its associated data are deleted. 

You can not combine these functions otherwise you'll see people having to always get back to the documentation to understand what that function does. Having 2 methods is the way to go

**Comment by nyamsprod** [comment]
- `Query::toParams` will be used to convert the string to an array similar to the result of  `parse_str`.
- `Query::getIterator` will iterate like Javascript `UrlSearchParams` while `Query::pairs` will iterate with the pair key as offset and the pair value as the returned value. Which means that the same offset could be found multiple times with the latter method
- query parsing and building is now offloaded to a dedicated package https://github.com/thephpleague/uri-query-parser
