### ISSUE TITLE
DataPath fails with strings starting with data:

### ISSUE THREAD

**Issue by nacmartin** [thephpleague/uri-components#2]
## Issue summary

This example from the documentation throws en error:

```php
use League\Uri\Components\DataPath;

$path = new DataPath('data:text/plain;charset=us-ascii,Hello%20World%21');
$path->isBinaryData(); // return false;
$newPath = $path->toBinary();
$newPath->isBinaryData(); //return true;
$newPath->toAscii()->sameValueAs($path); //return true;
```

The error is : "invalid mimeType, `data:text/plain`"

It doesn't seem to work with any string starting with `data` (so no data URI schemes)

### System informations

_(In case of a bug report Please complete the table below)_

| Information | Description |
|--------------|---------|
| league-uri-components version | 1.0.1  |
| PHP/HHVM version | 7.0.15 |
| OS Platform | macOS Sierra |

## Standalone code, or other way to reproduce the problem

See above

### Expected result

See above

### Actual result

See above

**Comment by nyamsprod** [comment]
@nacmartin this is a documentation error. The result your are getting is correct. If you want to normalize/validate a Data URI you need to use the [Data Uri class](http://uri.thephpleague.com/5.0/uri/schemes/data/). I'll bug fix the documentation
