### ISSUE TITLE
Cannot use League\Uri\Components\Exception as Exception because the name is already in use

### ISSUE THREAD

**Issue by jdme** [thephpleague/uri-components#21]
### Summary
Current version of `thephpleague/uri-components:>=1.7.0` is in conflict with `thephpleague/uri-parser`. I have a php compile error:
`Cannot use League\Uri\Components\Exception as Exception because the name is already in use`

Both packages are using same namespace `League\Uri` and `thephpleague/uri-parser` already have class `Exception` in this namespace.

### Workaround
Use fixed version 1.6.0 instead while this issue isn't fixed.

**Comment by nyamsprod** [comment]
hi @jdme,

Thanks for using this library. Could you please provide more info like the OS and PHP version you are using. Of note, these classes while having the same name do not belong in the same namespace one is in
`League\Uri` while the other is in `League\Uri\Components` so they should not collide unless I'm missing something.

**Comment by jdme** [comment]
Hi @nyamsprod,

> Could you please provide more info like the OS and PHP version you are using.

My system is macOS 10.12.6 and PHP 7.0.5

> Of note, these classes while having the same name do not belong in the same namespace one is in
`League\Uri` while the other is in `League\Uri\Components` so they should not collide unless I'm missing something.

Oh, sure, they belong to different namespaces, but _QueryParser.php_ has namespace `League\Uri`. 
So, when you do `use League\Uri\Components\Exception`, it tries to use class `Exception` in _QueryParser.php_, which already has another class with the same name from it's namespace.

To fix it, you should add an alias in _QueryParser.php_:
`use League\Uri\Components\Exception as Alias;`
