### ISSUE TITLE
Query encoding backward incompatibility in league/uri 4.2.*+

### ISSUE THREAD

**Issue by echernyavskiy** [thephpleague/uri-components#3]
## Issue summary

Upgrading to any league/uri version past 4.1.1 (including the 5.0.0 meta-package) results in queries being encoded differently than before (used to align with the output of `rawurlencode()`). See examples below.

### System information

| Information | Description |
|--------------|---------|
| league-uri-components version |  league/uri 4.2.*+|
| PHP/HHVM version |  5.x and 7.x|
| OS Platform |  Linux|

    $pairs = [
        'url' => 'https://google.com/?q=baz&a=b',
    ];
    $query = Query::createFromPairs($pairs);
    //var_dump($query->getContent($query::NO_ENCODING));
    //var_dump($query->getContent($query::RFC1738_ENCODING));
    //var_dump($query->getContent($query::RFC3987_ENCODING));
    var_dump($query->getContent($query::RFC3986_ENCODING));
    var_dump(key($pairs) . '=' . rawurlencode(end($pairs)));

### Expected result

    string(49) "url=https%3A%2F%2Fgoogle.com%2F%3Fq%3Dbaz%26a%3Db"
    string(49) "url=https%3A%2F%2Fgoogle.com%2F%3Fq%3Dbaz%26a%3Db"
    // as in http://foo.com?url=https%3A%2F%2Fgoogle.com%2F%3Fq%3Dbaz%26a%3Db

### Actual result

    string(35) "url=https://google.com/?q=baz%26a=b"
    string(49) "url=https%3A%2F%2Fgoogle.com%2F%3Fq%3Dbaz%26a%3Db"

**Comment by nyamsprod** [comment]
@echernyavskiy this is not a bug but expected behavior the change was made to make encoding and decoding URI component more RFC3986 compliant. In your example and prior to version 4.2, query parameters were over encoded for no good reason at all.

**Comment by echernyavskiy** [comment]
@nyamsprod I see. But then based on my example above it'd be

    http://foo.com?url=https://google.com/?q=baz%26a=b

vs.

    http://foo.com?url=https%3A%2F%2Fgoogle.com%2F%3Fq%3Dbaz%26a%3Db

How would a URL parser / consumer know where the query part begins? Simply assume that anything after the first _?_ is a query string?

Also is this a recent change in the referenced RFC? Working mostly with Drupal I didn't see this change surfacing in Drupal's built-in [url()](https://api.drupal.org/api/drupal/includes!common.inc/function/url/7.x) function - are other projects simply catching up on this?

**Comment by nyamsprod** [comment]
the query component starts at the first  `?` and contains everything after to the end of the URI or until the  `#` character is found as per RFC3986 definition

**Comment by echernyavskiy** [comment]
Understood, thanks. What about

> Also is this a recent change in the referenced RFC? Working mostly with Drupal I didn't see this change surfacing in Drupal's built-in url() function - are other projects simply catching up on this?

**Comment by nyamsprod** [comment]
> I don't know about Drupal enough I only know about the RFC. You should ask on a Drupal forum for more information. As for RFC3986, it has been release for more than a decade now.
