### ISSUE TITLE
Parameters escaping bug with rfc1738 encoding method

### ISSUE THREAD

**Issue by speto** [thephpleague/uri-components#37]
### Bug Report

Today I've encountered a problem with query building when one of the parameters is another url.
I've added tests at first to confirm the problem and briefly went step by step through xdebug. It looks like there could be problem in `QueryString` methods `buildPair` or `encodeMatches`. 

**According to tests/travisci:**
rfc1738 (problem with `=` equals sign)
```
--- Expected
+++ Actual
@@ @@
-'url=https%3A%2F%2Furi.thephpleague.com%2Fcomponents%2F2.0%2F%3Fmodule%3Dhome%23what-you-will-be-able-to-do+with+space'
+'url=https%3A%2F%2Furi.thephpleague.com%2Fcomponents%2F2.0%2F%3Fmodule=home%23what-you-will-be-able-to-do+with+space'
```

rfc3986 (problem with almost whole parameter)
```
--- Expected
+++ Actual
@@ @@
-'url=https%3A%2F%2Furi.thephpleague.com%2Fcomponents%2F2.0%2F%3Fmodule%3Dhome%23what-you-will-be-able-to-do%20with%20space'
+'url=https://uri.thephpleague.com/components/2.0/?module=home%23what-you-will-be-able-to-do%20with%20space'
```

| Information | Description |
|--------------|---------|
| Version |2.2.1|
| PHP version |7.2, 7.3, 7.4|
| OS Platform |Ubuntu, OS X|

#### Summary

`QueryString::build()` doesn't escape url in query properly.

#### Standalone code, or other way to reproduce the problem

```
$pairs = [['url', 'https://uri.thephpleague.com/components/2.0/?module=home#what-you-will-be-able-to-do with space']];

$querySringRfc1738 = QueryString::build($pairs, '&', PHP_QUERY_RFC1738); 
$querySringRfc3986 = QueryString::build($pairs, '&', PHP_QUERY_RFC3986); 
```

#### Expected result
Same as when you use `http_build_query`:
```
$http_build_query_rfc1738 = http_build_query([$pairs[0][0] => $pairs[0][1]], '', '&', PHP_QUERY_RFC1738);
var_dump($http_build_query_rfc1738);
//string(117) "url=https%3A%2F%2Furi.thephpleague.com%2Fcomponents%2F2.0%2F%3Fmodule%3Dhome%23what-you-will-be-able-to-do+with+space"
```

```
$http_build_query_rfc3986 = http_build_query([$pairs[0][0] => $pairs[0][1]], '', '&', PHP_QUERY_RFC3986);
var_dump($http_build_query_rfc3986);
//string(121) "url=https%3A%2F%2Furi.thephpleague.com%2Fcomponents%2F2.0%2F%3Fmodule%3Dhome%23what-you-will-be-able-to-do%20with%20space"
```

#### Actual result

rfc1738 (problem with `=` equals sign)
```
$querySringRfc1738 = QueryString::build($pairs, '&', PHP_QUERY_RFC1738);
var_dump($querySringRfc1738);
//string(115) "url=https%3A%2F%2Furi.thephpleague.com%2Fcomponents%2F2.0%2F%3Fmodule=home%23what-you-will-be-able-to-do+with+space"
```
rfc3986 (problem with almost whole parameter)
```
$querySringRfc3986 = QueryString::build($pairs, '&', PHP_QUERY_RFC3986);
var_dump($querySringRfc3986);
//string(105) "url=https://uri.thephpleague.com/components/2.0/?module=home%23what-you-will-be-able-to-do%20with%20space"
```

**Comment by nyamsprod** [comment]
@speto thanks for the lengthy bug report,  I've read it and here's my take

first thing first, `http_build_query` should never be used as a basis of how encoding should be performed as the function pre-date any current stable RFC or Web standard specification. And the following package tries to be compliant against those standard not against `http_build_query`.

Having said that, let me go into more details:

Regarding RFC3986, [the specification is clear](https://tools.ietf.org/html/rfc3986#section-3.4):

> The query component is indicated by the first question mark ("?") character and terminated by a number sign ("#") character or by the end of the URI.

Also of note, in RFC3986, the following characters `=` and `&` have *no* particular meanings.
And last but not least double encoding should be avoided. If you take into account all theses requirement you will end up with the current behaviour. Simply put, the RFC3986 current encoding mechanism is the expected one and as such is not a bug.

Regarding RFC1738 encoding, the encoding I've choose to implement is the one specified by the [WHATG](https://url.spec.whatwg.org/). After re-reading the specification and looking at its [extensive test suite](https://github.com/web-platform-tests/wpt/tree/master/url) I can confirm that the only bug is that the `=` should indeed be url encoded to `%3D`. That's the only bug that I could confirm.

Of course your can submit a PR to resolve that one bug and if so I would be pleased to review your PR.
