### ISSUE TITLE
Query::createFromPairs have TypeError

### ISSUE THREAD

**Issue by iLexN** [thephpleague/uri-components#44]
### Bug Report

_(Fill in the relevant information below to help triage your issue.)_

| Information | Description |
|--------------|---------|
| Version | 2.2 | 
| PHP version | 7.2 / 7.3 |
| OS Platform | linux  |

#### Summary

Follow the doc, https://uri.thephpleague.com/components/2.0/query/#using-the-query-as-a-collection-of-query-pairs.

follow the example

```php 
$query =  Query::createFromPairs([
    'foo' => 'bar',
    'p' => 'yolo',
    'z' => ''
]);
echo $query; //display 'foo=bar&p=yolo&z='

$query =  Query::createFromPairs([
    'foo' => 'bar',
    'p' => null,
    'z' => ''
]);
echo $query; //display 'foo=bar&p&z='

```
the example code have error.

```
TypeError: Argument 1 passed to League\Uri\QueryString::buildPair() must be of the type array, string given, called in /var/www/vendor/league/uri-components/src/QueryString.php on line 257 in League\Uri\QueryString::buildPair() (line 278 of /var/www/vendor/league/uri-components/src/QueryString.php).
```

#### Standalone code, or other way to reproduce the problem

```php
<?php
declare(strict_types=1);

use League\Uri\Components\Query;

include 'vendor/autoload.php';

$query =  Query::createFromPairs([
    'foo' => 'bar',
    'p' => 'yolo',
    'z' => ''
]);
echo $query; //display 'foo=bar&p=yolo&z='

$query =  Query::createFromPairs([
    'foo' => 'bar',
    'p' => null,
    'z' => ''
]);
echo $query; //display 'foo=bar&p&z='
```

#### Expected result

display ` foo=bar&p=yolo&z=`

display `foo=bar&p&z=`

same as the example.

#### Actual result

_(What is the current (buggy) behavior?)_

```
TypeError: Argument 1 passed to League\Uri\QueryString::buildPair() must be of the type array, string given, called in /var/www/vendor/league/uri-components/src/QueryString.php on line 257 in League\Uri\QueryString::buildPair() (line 278 of /var/www/vendor/league/uri-components/src/QueryString.php).
```

**Comment by iLexN** [comment]
I found that the doc example is wrong.

below code work

```php
$query =  Query::createFromPairs([
    ['foo' , 'bar'],
    ['p' , 'yolo]'],
    ['z' , ''],
]);
echo $query; //display 'foo=bar&p=yolo&z='

$query =  Query::createFromPairs([
    ['foo' , 'bar'],
    ['p' , null],
    ['z' , '']
]);
echo $query; //display 'foo=bar&p&z='
```

may need update the doc example code(https://uri.thephpleague.com/components/2.0/query/#using-the-query-as-a-collection-of-query-pairs).

or maybe also upgrade page (https://uri.thephpleague.com/components/2.0/upgrading/), cause i am upgrade from 1.x 

version 1 work for
```php
$query =  Query::createFromPairs([
    'foo' => 'bar',
    'p' => 'yolo',
    'z' => ''
]);
echo $query; //display 'foo=bar&p=yolo&z=
```

Finally, Thank for your work.

**Comment by nyamsprod** [comment]
@iLexN thanks for the issue opened ? So if I understood the issue was that the documentation was wrong ... but the code is working ... but differently that in v1 right ? 🤔

**Comment by iLexN** [comment]
I am not sure which part go wrong. cause it is major version change, may not backwards compatible.

in v1.x, this **work**
```php
$query =  Query::createFromPairs([
    'foo' => 'bar',
    'p' => 'yolo',
    'z' => ''
]);
echo $query; //display 'foo=bar&p=yolo&z=
```

in v2, it is **not work** with the example code (https://uri.thephpleague.com/components/2.0/query/#using-the-query-as-a-collection-of-query-pairs)
```php
$query =  Query::createFromPairs([
    'foo' => 'bar',
    'p' => 'yolo',
    'z' => ''
]);
echo $query; //display 'foo=bar&p=yolo&z=
```

in v2 , it **work** (i find the example in the test case, https://github.com/thephpleague/uri-components/blob/master/tests/Components/QueryTest.php#L176)
```php 
$query =  Query::createFromPairs([
    ['foo' , 'bar'],
    ['p' , 'yolo]'],
    ['z' , ''],
]);
echo $query; //display 'foo=bar&p=yolo&z='
```

if v2 `Query::createFromPairs` is not compatible with v1, than the doc example is wrong.


Thank for looking into this issue.

My english not good, i try to explain what i find.

**Comment by nyamsprod** [comment]
@iLexN got it. Indeed this was an intentional BC break the named constructor you are looking for is called  `creatrFromParams` in v2.

**Comment by iLexN** [comment]
Thanks for your suggestion.

change the method from `createFromPairs` to `Query::createFromParams` more easy for upgrade, no need reformat the data.

**Comment by nyamsprod** [comment]
@iLexN seems both constructors were already explained in the documentation will close this issue
