### ISSUE TITLE
PHP 8

### ISSUE THREAD

**Issue by Eldair** [thephpleague/uri-components#45]
### Question

Hello, I see there were commits for PHP 8 support but no release, is it coming soon?

**Comment by nyamsprod** [comment]
@Eldair it will be released once the codebase is ready. I've added a couple of other features that still needs to be documentated at least in the changelog. Once that is done the release will be created.
You can of course help me speed up the process by making a diff between master and the last release and document the new features as well. This is an open source package any help is always welcomed.

**Comment by stayallive** [comment]
I did a quick scan and although I'm not familiar with the internals of this package the changelog looks really complete and I couldn't find anything that needs adding, could you be a little more specific in what you need help in getting the release out of the door so we can start enjoying PHP 8 with this package too 😄 

For ref, I checked this diff: [`2.2.1...master`#diff-06572a96a5](https://github.com/thephpleague/uri-components/compare/2.2.1...master#diff-06572a96a58dc510037d5efa622f9bec8519bc1beab13c9f251e97e657a9d4ed)

**Comment by nyamsprod** [comment]
version 2.3.0 is released with support for PHP8.0 see the release notes for more info 
https://github.com/thephpleague/uri-components/releases/tag/2.3.0
