### ISSUE TITLE
using closing bracket `]` in key will leave out all data after it

### ISSUE THREAD

**Issue by hrvoj3e** [thephpleague/uri-components#48]
### Bug Report

| Information | Description |
|--------------|---------|
| Version | 2.3.0 |
| PHP version | 8.0.5 |
| OS Platform | Ubuntu 20 LTS |

#### Summary

Using closing bracket `]` in key will leave out all data after it.

> Similar problems: https://github.com/ljharb/qs/issues/235

#### Standalone code, or other way to reproduce the problem

```php
$urlQuery = 'zzz=yyy&aaaa[%5Bbbb%5Dxyz]=%5Bccc%5Dxyz';
$parsed = \League\Uri\QueryString::extract($urlQuery, '&', PHP_QUERY_RFC3986);
var_export($parsed); // array ( 'zzz' => 'yyy', 'aaaa' => array ( '[bbb' => '[ccc]xyz', ), )
$parsed = \League\Uri\QueryString::extract($urlQuery, '&', PHP_QUERY_RFC1738);
var_export($parsed); // array ( 'zzz' => 'yyy', 'aaaa' => array ( '[bbb' => '[ccc]xyz', ), )
```

#### Expected result

```php
// PHP_QUERY_RFC3986
// array ( 'zzz' => 'yyy', 'aaaa' => array ( '[bbb]xyz' => '[ccc]xyz', ), )
// PHP_QUERY_RFC1738
// array ( 'zzz' => 'yyy', 'aaaa' => array ( '[bbb]xyz' => '[ccc]xyz', ), )
```

#### Actual result
Key should be `'[bbb]xyz'` and not `'[bbb'`

```php
// PHP_QUERY_RFC3986
// array ( 'zzz' => 'yyy', 'aaaa' => array ( '[bbb' => '[ccc]xyz', ), )
// PHP_QUERY_RFC1738
// array ( 'zzz' => 'yyy', 'aaaa' => array ( '[bbb' => '[ccc]xyz', ), )
```

**Comment by nyamsprod** [comment]
@hrvoj3e thanks for using the library. 

This is an expected behaviour as it matches the behaviour of `parse_str` as [explain in the documentation](https://uri.thephpleague.com/components/2.0/query-parser-builder/#extracting-php-variables)

**Comment by hrvoj3e** [comment]
@nyamsprod is there a way with this lib to get what I want?
> Key should be '[bbb]xyz' and not '[bbb'

**Comment by nyamsprod** [comment]
@hrvoj3e if you want to preserve data you are require to use `Query::parse`, `Query::extract` only differ from the native PHP function in that it fixes variable mangling.

**Just like `parse_str` and the superglobal `_GET`, `Query::extract` is meant to convert query string into PHP variables not to preserve data.**

**Comment by hrvoj3e** [comment]
OK. Will try with `parse`.
Are you open to adding a method that works like `extract` (nested arrays) but uses preserved data from `parse`?
I will write my own but I think it would be nice to get it out of the box in this lib.

**Comment by nyamsprod** [comment]
@hrvoj3e I am open to anything after careful review but I guess you know by now that's not possible to preserve data because with the way `parse_str` works ?

How do you preserve  the following query string `foo=bar&foo=baz` ??

**Comment by hrvoj3e** [comment]
I get that it uses the last value only.
I am mainly interested to preserve keys - that should be possible.

```php
$urlQuery = 'zzz=yyy&aaaa[%5Bbbb%5Dxyz]=%5Bccc%5Dxyz&zzz=www';
/*
[
    'zzz' => 'www',
    'aaaa' => [
        '[bbb]xyz' => '[ccc]xyz',
    ],
]
*/ 
```

**Comment by nyamsprod** [comment]
no it won't be because brackets have a specific meaning: they are used to create arrays in PHP variables. Since everything is URL decoded before extraction the parsing will stop on the first incoherence and bail out. That is what is happening in your case. 

Anyway you now know the root cause of your issue and why it is like this 👍🏾
